<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => 'Блог',
    'Create' => 'Создайте',
    'Create Subject' => 'Создать предмет',
    'Delete' => 'Удалять',
    'Lessons' => 'Уроки',
    'Menu' => 'Меню',
    'Promotional Code' => 'Промо код',
    'Section' => 'Раздел',
    'Sections' => 'Разделы',
    'Subject' => 'Предмет',
    'Subjects' => 'Предметы',
    'Teachers' => 'Учителя',
    'Update' => 'Обновить',
    'Users Access' => 'Доступ пользователя',
    'Are you sure you want to delete this item?' => '',
    'Assignment' => 'Назначение',
    'Create Menu' => 'Создать меню',
    'Create Section' => 'Создать раздел',
    'Create Sections' => 'Создать разделы',
    'Create Subjects' => 'Создать темы',
    'Menus' => 'Меню',
    'Permission' => 'Разрешение',
    'Reset' => 'Сброс',
    'Role' => 'Роль',
    'Route' => 'Маршрут',
    'Search' => 'Поиск',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
//    'Update Section: {name}' => 'Обновить раздел: {имя}',
//    'Update Subjects: {name}' => 'Предметы обновления: {имя}',
];
