<?php

namespace frontend\modules\api;

use Yii;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'frontend\modules\api\controllers';

    const MODULE = "api";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
