<?php

namespace frontend\modules\api\controllers;

use Cassandra\Exception\UnauthorizedException;
use common\models\Auth;
use common\models\Menu;
use common\models\Options;
use common\models\Session;
use frontend\models\User;
use frontend\modules\api\components\Select;
use frontend\modules\api\controllers\service\MainService;
use yii\base\Controller;
use yii\helpers\Html;
use yii\web\ForbiddenHttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;
use  Yii;

class MainController extends Controller
{
    /**
     * @var MainService
     */
    private $mainService;

    /**
     * {@inheritDoc}
     */
    public function behaviors()
    {
        return [
            'PrBlockFilter' => [
                'class' => 'app\components\filters\PrBlockFilter',
            ]
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function init()
    {
        $this->mainService = new MainService();
        \Yii::$app->response->format = Response::FORMAT_JSON;
        parent::init();
    }

    public function actions()
    {
        \Yii::$app->user->loginUrl = '/site/test/';
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return [];
    }

    public function actionUser()
    {

        $session =
            Session::find()
                ->where(['user_id' => \Yii::$app->user->id])
                ->andWhere(['!=', 'user_id', ''])
                ->orderBy(['expire' => SORT_DESC])->asArray()->one();

        if (empty($session)) {
            throw new UnauthorizedHttpException();
        }

        return [
            'status' => 200,
            'user' => [
                'username' => \Yii::$app->user->identity['username'],
                'email' => \Yii::$app->user->identity['email'],
                'access_token' => \Yii::$app->user->identity['auth_key'],
                'session' => $session,
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionMenu()
    {
        $model = Select::receiveAllData(new Menu());
        return
            [
                'status' => 200,
                'data' => $model,
            ];
    }

    /**
     * @return array | bool
     */
    public function actionInit()
    {
        $result =
            [
                'status' => 200,
                'data' => [],
            ];

        $request = Yii::$app->request;
        $data = $request->getBodyParam('data');

        Yii::info('ololo: '.serialize($data), __METHOD__);

        $mainService = $this->mainService;
        $getRequest = \Yii::$app->request->get();

        if (isset($getRequest['mid'])) {
            $auth = $mainService->findAuth(Html::encode($getRequest['mid']));

            if (isset($auth->user)) {
                $result = $mainService->receiveCurrentUser($auth->user);
            }
        }

        return $result;
    }

    /**
     * @return string
     */
    public function actionOptions()
    {
        $model = Options::find()->asArray()->all();

        $optionsData = [];

        foreach ($model as $option) {
            $optionsData[$option['key']][] = \Opis\Closure\unserialize($option['value']);
        }

        return
            [
                'status' => 200,
                'data' => $optionsData,
            ];
    }
}
