<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignment' => 'Назначение',
    'Background' => 'Фон',
    'Blog' => 'Блог',
    'Bonus Points' => 'Баллы',
    'City' => 'Город',
    'Correct Answer' => 'Правильный ответ',
    'Create' => 'Создайте',
    'Create Menu' => 'Создать меню',
    'Create Quiz' => 'Создать викторину',
    'Create Section' => 'Создать раздел',
    'Create Sections' => 'Создать разделы',
    'Create Subject' => 'Создать предмет',
    'Create Subjects' => 'Создать темы',
    'Created At' => 'Создано ',
    'Delete' => 'Удалять',
    'Description' => 'Описание',
    'First Name' => 'Имя',
    'Hint' => 'Подсказка',
    'Icon' => 'Икона',
    'Img Name' => 'Изображения',
    'Is Status' => 'Статус',
    'Key' => 'Ключ',
    'Last Name' => 'Фамилия',
    'Lessons' => 'Уроки',
    'Lessons ID' => 'ID урока',
    'Logo' => 'Логотип',
    'Menu' => 'Меню',
    'Menus' => 'Меню',
    'Name' => 'Имя',
    'Parent ID' => 'ID родителя',
    'Permission' => 'Разрешение',
    'Phone' => 'Телефон',
    'Position' => 'Позиция',
    'Price' => 'Цена',
    'Promotional Code' => 'Промо код',
    'Question' => 'Вопрос',
    'Quiz' => 'Тесты',
    'Quiz ID' => 'ID теста',
    'Quizzes' => 'Тесты',
    'Rating' => 'Рейтинг',
    'Reset' => 'Сброс',
    'Role' => 'Роль',
    'Route' => 'Маршрут',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Section' => 'Раздел',
    'Section ID' => 'ID раздела',
    'Sections' => 'Разделы',
    'Seo Description' => 'Сео Описание',
    'Seo Keywords' => 'SEO Ключевые слова',
    'Short Description' => 'Краткое описание',
    'Subject' => 'Предмет',
    'Subjects' => 'Предметы',
    'Teachers' => 'Учителя',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Title' => 'Заглавие',
    'Update' => 'Обновить',
    'Updated At' => 'Обновлен',
    'Users Access' => 'Доступ пользователя',
    'Active' => 'Активный',
    'Are you sure you want to delete this item?' => '',
    'ID' => '',
    'Inactive' => 'Неактивный',
    'Slug' => '',
    'Sort Lessons' => '',
    'Subject ID' => '',
    'Subjects ID' => '',
    'Update Quiz: {name}' => '',
    'Update Section: {name}' => '',
    'Update Subjects: {name}' => '',
    'User ID' => '',
];
