<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '',
    'Active' => '',
    'Add Book' => '',
    'Are you sure to delete this item?' => '',
    'Book Listing' => '',
    'Clear selection' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Delete' => '',
    'Download Selected' => '',
    'Expand' => '',
    'Expand All' => '',
    'Failed to update editable data due to an unknown server error' => '',
    'Inactive' => '',
    'Invalid editable index or model form name' => '',
    'Invalid or bad editable data' => '',
    'Library' => '',
    'No data found' => '',
    'No valid editable model found' => '',
    'Reset Grid' => '',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => '',
    'The table header sticks to the top in this demo as you scroll' => '',
    'Update' => '',
    'View' => '',
    'export' => '',
];
